spring.application.name=notification-api

server.port=8081

logging.file.path=logs

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/notifydb?TimeZone=UTC
spring.datasource.username=notifyuser
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
notification.kafka.topic=notifications.pending

# Producer Serialization
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.kafka.producer.properties.spring.json.add.type.headers=false